### ISSUE TITLE
Not able to display the truth or dare when clicked buttons

### ISSUE THREAD

**Issue by saikiranmastermind** [sylhare/Truth-or-Dare#12]
when we click on truth or dare buttons. the responsible truth or dare are not displayed belows.
could you please help.

Attaching the screenshot
<a href="https://ibb.co/fxkLWWY"><img src="https://i.ibb.co/W2kjXXW/truthordareerror.jpg" alt="truthordareerror" border="0"></a>

**Comment by sylhare** [comment]
Allo did you try on another browser?
Maybe it is not compatible with the version you are using. 

Did you try locally or online? Do you see any errors in your browser `developer` tab (look in the console).

**Comment by saikiranmastermind** [comment]
First downloaded by direct clicking on the clone or download.
From that code, I got this error, later when I download from the releases section. then the code is working. I think there is some update missing or anything. 

Finally, from the releases section, it's working perfectly, thanks for the code.

**Comment by sylhare** [comment]
Ah great :+1:
