### ISSUE TITLE
Input file does not load

### ISSUE THREAD

**Issue by FrankDMartinez** [sylhare/Truth-or-Dare#13]
Hello.

When I start up the application, the browser console says "output.json" could not be found and, even though manually uploading supposedly succeeds, no questions nor dare ever appear in the window. This can be reproduced using the demo site.

What additional information do you require to diagnose the issue?

Thanks in advance.

**Comment by sylhare** [comment]
The demo can't load file, so it's normal.
Usually it works better with Firefox, which browser are you using?

Do you have a piece of the `output.json`?

**Comment by FrankDMartinez** [comment]
I use Chrome.

I keep a copy of the `output.json` [here](https://pastebin.com/HsLTkVrh).

**Comment by sylhare** [comment]
It seems I have trouble downloading the file. Can you paste here the couple first lines and the couple last lines?

Did you create it with the script?
Did you try the example one?

**Comment by FrankDMartinez** [comment]
Opening lines:
```
[
  {
    "id": "0",
    "type": "Dare",
    "level": "2",
    "summary": "I dare you to Stand up for 2 turns",
    "time": "",
    "turns": "2"
  },
  {
    "id": "1",
    "type": "Dare",
    "level": "2",
    "summary": "I dare you to do 10 pushups with one hand in less than a minute",
    "time": "60",
    "turns": ""
  },
  {
    "id": "2",
    "type": "Truth",
    "level": "2",
    "summary": "What actor\/actress do you prefer?",
    "time": "",
    "turns": ""
  },
  {
    "id": "3",
    "type": "Truth",
    "level": "3",
    "summary": "Who is your secret crush?",
    "time": "",
    "turns": ""
  },
```

Closing lines:
```
{
    "id": "421",
    "type": "Dare",
    "level": "2",
    "summary": "Pretend that you're swimming underwater for the next three rounds of questions. Don't forget to make bubbling noises and come up for air from time to time.",
    "time": "",
    "turns": "3"
  },
  {
    "id": "422",
    "type": "Dare",
    "level": "2",
    "summary": "Everything you say for the rest of the game has to rhyme.",
    "time": "",
    "turns": "40"
  },
  {
    "id": "423",
    "type": "Dare",
    "level": "2",
    "summary": "Repeat everything another player says for the next three rounds of the game.",
    "time": "",
    "turns": "3"
  },
  {
    "id": "424",
    "type": "Dare",
    "level": "2",
    "summary": "Sing instead of speaking for the next two rounds of the game.",
    "time": "",
    "turns": "2"
  }
]
```

The file was produced using the command `python3.7 csv_to_json.py`.

**Comment by sylhare** [comment]
Ok I know why, it is because of stricter CORS policy on the browser. It would need to re engineer a part of the code.
Or directly use the json within the javascript instead of loading it.

**Comment by FrankDMartinez** [comment]
Would you recommend a different browser? Or is there a setting I can change on the Chrome browser?

**Comment by sylhare** [comment]
Or in the mean time you can use an addon that enable CORS on your browser.
