### ISSUE TITLE
Translate the website

### ISSUE THREAD

**Issue by airon90** [sylhare/Truth-or-Dare#3]
Please, could you change the code so that the website can be translated into other languages?

**Comment by sylhare** [comment]
Hi @airon90 ,

What do you mean by that? Like having the text in a difference file and have multiple translation of it?
How would you do it?

**Comment by sylhare** [comment]
For the questions, you can upload them from a csv file in the language you like or and use it locally.

**Comment by airon90** [comment]
I don't mean to translate questions, although it would be nice to have multilingual demo questions.
I mean the website itself:  [this](https://github.com/sylhare/Truth-or-Dare/blob/master/src/js/script.js#L124), [this](https://github.com/sylhare/Truth-or-Dare/blob/master/src/js/script.js#L171), [this](https://github.com/sylhare/Truth-or-Dare/blob/master/src/js/script.js#L527), [this](https://github.com/sylhare/Truth-or-Dare/blob/master/src/index.html#L44), [this](https://github.com/sylhare/Truth-or-Dare/blob/master/src/index.html#L85), ... are hardcoded English strings.
I could look for some tips in order to reach the solution for this feature request, as long as you are interested ;)

**Comment by sylhare** [comment]
It's a bit of an old project that I made for fun, and to learn. However I was thinking of adding tests and maybe refactor the code a bit.
I was thinking maybe of using a yaml file or something, have a second version using nodeJS maybe.

The easiest thing would be to use at least a config file for those hard coded piece, I would be glad with that, if you wanna push something, I'd be interested! 👍

**Comment by airon90** [comment]
> if you wanna push something, I'd be interested!
I would really want to help you but I just code in Python, C and Matlab lol
I should learn more languages :(
Otherwise I would have already written to you that I would have taken care of this

**Comment by sylhare** [comment]
Ok, I will add the tag `help wanted` and if I have time, I might take a look at it 😉
