### ISSUE TITLE
Settings are not considered

### ISSUE THREAD

**Issue by airon90** [sylhare/Truth-or-Dare#6]
If you choose "Sexy" experience in the default settings, even non-sexy option will be choosen by app

**Comment by sylhare** [comment]
It might be because the excel file for the demo was changed, or that I had put random score on questions. I will look at it.

**Comment by sylhare** [comment]
Oh I know, I have removed the `hot` and `sexy` questions from the demo. So since there are none it may take at random. I guess you would need to add your own question for the game. I will look into #8 so it will be easier for you 😉 and close this one.

**Comment by airon90** [comment]
This bug is open yet. You removed "hot" and "sexy" questions from demo (unfortunately :D) but a system should detect which categories are available and remove those unavailable

**Comment by sylhare** [comment]
Ahah, yes I thought it might not be "github appropriate" ot too NSFW 😅 I had found them browsing around. They should still be in the git tree though.

Having the choices disappear would be indeed better, so users do not get fooled by the system.

**Comment by airon90** [comment]
> Ahah, yes I thought it might not be "github appropriate" ot too NSFW :sweat_smile:  I had found them browsing around. They should still be in the git tree though.

That is your choice, I am not judging that, although you could have added a separate NSFW csv file  :P

> Having the choices disappear would be indeed better, so users do not get fooled by the system.

That is why you should reopen this bug report ;)
